executable =/bin/bash
accounting_group = LongJob.Weekly
request_memory = 40G
request_cpus = 24
concurrency_limits = XXX_limit:874

getenv = True

Exp = WT_rep3

NanoTimingDir = YourChoice
path2work = $(NanoTimingDir)/$(Exp)

batch_name = nanoT_prep_$(Exp)
arguments =$(path2work)/$(batch_name).sh

output = $(path2work)/logs/$(batch_name).out
error = $(path2work)/logs/$(batch_name).err
log = $(path2work)/logs/$(batch_name).log

queue
